### ISSUE TITLE
messy code when there are chinese in data

### ISSUE THREAD

**Issue by johnzhu12** [maxogden/csv-write-stream#41]
I have exported the data-list successfully. but my headers and some data characters have chinese . they turn to messy code like "烫烫烫"。
 so .is there any setting there to set the unicode

**Comment by johnzhu12** [comment]
ok,change to use json2csv,thanks anyway,close this one

**Comment by notslang** [comment]
Could you create a test case to reproduce this in https://github.com/maxogden/csv-write-stream/blob/master/test.js?

**Comment by yunfan** [comment]
@johnzhu12  i happened to met this too, and the problem caused by the lack of UTF8 BOM for MS platform

the issue could be solved by  adding a UTF8 BOM at the beginning of the target csv file
and then feed that stream to writer.pipe
for example, if the previous code is
```javascript

const csvWriter = require('csv-writer-stream');

let data = [{a: 1, b: 2}, {a:1, b:2}, {a:1, b:2}];

let writer = csvWriter({newline: '\r\n'});
writer.pipe(fs.createWriteStream(path.join("taraget.csv"));
for(let row of data){ writer.write(row); }
writer.end();

```

now it could be replaced by adding a preaction like
```javascript


const csvWriter = require('csv-writer-stream');

let data = [{a: 1, b: 2}, {a:1, b:2}, {a:1, b:"中文"}];

let writer = csvWriter({newline: '\r\n'});

// changing begin
let target_fd = fs.createWriteStream(path.join("taraget.csv");
await target_fd.write(Buffer.from([0xef, 0xbb, 0xbf]));
writer.pipe(target_fd);
// changing end

for(let row of data){ writer.write(row); }
writer.end();


```

@slang800  i am new to nodejs, not be familliar with those testing tools, would be please add this behavior as a init option? like  `{BOM: Buffer.from([0xef, 0xbb, 0xbf]), newline: '\r\n'}`  the BOM could be configured to support utf8 or utf16 if the user has that demand
